/*

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuCGEXqnlUH2gSOcV-ctv8hSYu_cPVL20',
    appId: '1:814631717041:web:e72e12d938ce736e703a90',
    messagingSenderId: '814631717041',
    projectId: 'pushnotification-4f836',
    authDomain: 'pushnotification-4f836.firebaseapp.com',
    storageBucket: 'pushnotification-4f836.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClbogxdCgdbTahbq5mrjBOZDxtPYfgeww',
    appId: '1:814631717041:android:e78162fe7f9da541703a90',
    messagingSenderId: '814631717041',
    projectId: 'pushnotification-4f836',
    storageBucket: 'pushnotification-4f836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKnHEj1ZPQbx9zEDI09TN969ZHYUc6PKk',
    appId: '1:814631717041:ios:470148cfa8129bda703a90',
    messagingSenderId: '814631717041',
    projectId: 'pushnotification-4f836',
    storageBucket: 'pushnotification-4f836.appspot.com',
    iosBundleId: 'com.example.deticApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKnHEj1ZPQbx9zEDI09TN969ZHYUc6PKk',
    appId: '1:814631717041:ios:c513bd5ae785e232703a90',
    messagingSenderId: '814631717041',
    projectId: 'pushnotification-4f836',
    storageBucket: 'pushnotification-4f836.appspot.com',
    iosBundleId: 'com.example.deticApp2.RunnerTests',
  );
}
*/